#!/usr/bin/env bash

# this is based on a test file
# we are assuming what is in the file is the current month
# instead of `cat last.fake` it would be last -s $(date +'%Y-%m-00')

users=$(cat last.fake | sed -E 's/([^ ]+) +.+/\1/' | sort | uniq -c | sort -nr)
new_usernames=""
echo "a"
while read user; do
  count=$(echo "$user" | cut -f1)
  username=$(echo "$user" | cut -f2)
  new_usernames+="$count"
  echo "$(sed -E -n "s/^$username:([^:]+:){3}([^:]+):.*/\2/p" passwd.fake)"
done <<< "$users"
echo "$new_usernames"
